#!/bin/sh
cd "${0%/*}" || exit                         # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions # Tutorial run functions
#------------------------------------------------------------------------------

touch cavity.foam # Создаем файл для визуализации
runApplication blockMesh               # Создаем сетку
restore0Dir                            # Создаем нулевой момент
runApplication $(getApplication)       # Запускаем расчёт

#------------------------------------------------------------------------------
